# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: harrysLaptop

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@latest
    npm install
    ng build --prod
  displayName: 'npm install and build'


# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Free Trial (a4df00e4-10ee-4f09-a997-2bbde12baabc)'
#     appType: 'webApp'
#     WebAppName: 'harryPersonal'
#     packageForLinux: 'dist/'

- task: PublishBuildArtifacts@1

